export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const LOGOUT_USER = 'LOGOUT_USER'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const SEARCH_CONTACT_BEGIN = 'SEARCH_CONTACT_BEGIN'
export const SEARCH_CONTACT_SUCCESS = 'SEARCH_CONTACT_SUCCESS'
export const SEARCH_CONTACT_ERROR = 'SEARCH_CONTACT_ERROR'

export const ADD_CONTACT_BEGIN = 'ADD_CONTACT_BEGIN'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'
export const ADD_CONTACT_ERROR = 'ADD_CONTACT_ERROR'

export const GET_USERS_BEGIN = 'GET_USERS_BEGIN'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const GET_MSGS_BEGIN = 'GET_MSGS_BEGIN';
export const GET_MSGS_SUCCESS = 'GET_MSGS_SUCCESS';

export const CREATE_MSG_BEGIN = 'CREATE_MSG_BEGIN';
export const CREATE_MSG_SUCCESS = 'CREATE_MSG_SUCCESS';
export const CREATE_MSG_ERROR = 'CREATE_MSG_ERROR';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

